name: citibike_hourly_features_pipeline

on:
  schedule:
    - cron: '2 * * * *'  # ⏰ Run every hour (2 minutes after the hour)
  workflow_dispatch:    # 🚀 Allow manual trigger from GitHub UI

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # ✅ Using Python 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_feature_pipeline.txt
          pip install lightgbm  # 🔥 Add this manually to avoid ModuleNotFoundError

      - name: Run Citi Bike feature pipeline and load to Hopsworks
        env:
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
        run: |
          python -m src.interface_pipeline
