name: citibike_hourly_inference_pipeline

on:
  workflow_run:
    workflows: ["citibike_hourly_features_pipeline"]  # ✅ Trigger after feature engineering finishes
    types:
      - completed
  workflow_dispatch:  # 🚀 Also allow manual triggering from GitHub UI

jobs:
  run-inference:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # ✅ Python 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # ✅ General dependencies

      - name: Run Citi Bike hourly inference pipeline
        env:
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
        run: |
          python -m src.interface_pipeline
